# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
	imports = [
		<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
	];

	boot = {
		initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
		kernelModules = [ "kvm-intel" "tp_smapi" ];
		extraModulePackages = [ config.boot.kernelPackages.tp_smapi ];
		blacklistedKernelModules = [ "pcspkr" ];

		loader.grub = {
			enable = true;
			version = 2;
		};

		loader.efi.canTouchEfiVariables = true;

		cleanTmpDir = true;
	};

	hardware = {
		opengl = {
			enable = true;
			extraPackages = [ pkgs.vaapiIntel ];
		};

		pulseaudio.enable = true;
	};

	powerManagement.enable = true;

	services = {
		xserver = {
			layout = "uk";
			xkbModel = "thinkpad60";
			xkbOptions = "eurosign:e";

			videoDrivers = [ "intel" ];
		};

		acpid.enable = true;

		thinkfan = {
			enable = true;
			sensor = "/sys/class/hwmon/hwmon2/temp1_input";
		};

		tlp.enable = true;
	};

	i18n = {
		consoleKeyMap = "uk";
		defaultLocale = "en_GB.UTF-8";
	};

	sound.enableMediaKeys = true;

	nix.maxJobs = lib.mkDefault 4;
}
